charset_normalizer/legacy.py
charset_normalizer/probe_chaos.py
test/test_on_byte.py

This PR fixes #13 #12 
Still, be careful with tiny content. Still looking for a better way to solve the problem.

Bugfix release 1.1.0

---

charset_normalizer/normalizer.py
charset_normalizer/probe_coherence.py
setup.py
test/test_cli.py

This PR fixe a bug when positional parameters steps and chunk_size were not fitted to content.
This mistake could lead to misdetection on small content. :-1:

Adapt chunk_size and steps according to sequence len

---

charset_normalizer/__init__.py
charset_normalizer/version.py
setup.py

Permit such as 
```python
import charset_normalizer
print(charset_normalizer.__version__)
```

Expose __version__ in package

---

README.md
charset_normalizer/cached_property/__init__.py
charset_normalizer/cli/normalizer.py
charset_normalizer/normalizer.py
setup.py

➖ Also, drop PrettyTable dependency

:sparkle: CLI now produce JSON consumable output

---

charset_normalizer/api.py

:art: Public function normalize default args are not aligned with from_bytes

---

.github/workflows/integration.yml
bin/integration.py
bin/requirements.txt
bin/serve.py

This will automate some tests with requests.

:heavy_check_mark: Initial integration testing with requests (basic)

---

.github/workflows/chardet-bc.yml
.github/workflows/detector-coverage.yml
.github/workflows/performance.yml
.github/workflows/run-tests.yml
README.md
charset_normalizer/api.py
charset_normalizer/cli/normalizer.py
charset_normalizer/md.py
charset_normalizer/models.py
charset_normalizer/utils.py
charset_normalizer/version.py
tests/test_probe_chaos.py

*Changes:*
- **Bugfix:** 🐛 The CLI no longer raise an unexpected exception when no encoding has been found (#70)
- **Improvement:** ❇️ Adjust the MD to lower the sensitivity, thus improving the global detection reliability (#69 #76) 
- **Bugfix:** 🐛 Fix accessing the 'alphabets' property when the payload contains surrogate characters (#68)
- **Internal:** 🎨  Fix line endings from CRLF to LF for certain files (#67)
- **Bugfix:** 🐛 ✏️ The logger could mislead (explain=True) on detected languages and the impact of one MBCS match (in #72) 
- **Bugfix:** 🐛 Submatch factoring could be wrong in rare edge cases (in #72)
- **Improvement:** ❇️ Allow fallback on specified encoding if any (#71)
- **Bugfix:** 🐛 Multiple files given to the CLI were ignored when publishing results to STDOUT. (After the …

🔖  Bump version to 2.0.4

---

MANIFEST.in
dev-requirements.txt

:art: Add missing files/dir in MANIFEST.in

---

README.md
charset_normalizer/models.py
docs/advanced_search.rst
tests/test_base_detection.py

\+ refresh url characters freq from simia.net
before 
```python
results = from_bytes(...)
if len(results):
...
```
after
```python
results = from_bytes(...)
if results:
...
```

:art: Sugar syntax to verify if CharsetMatches contain at least one entry

---

README.md
charset_normalizer/version.py

*Changes:*
**Internal:** :art: The project now comply with: flake8, mypy, isort and black to ensure a better overall quality #81 
**Internal:** :art: The MANIFEST was not exhaustive and one could fail to run the tests in certain cases #78 
**Improvement:** :sparkles: The BC-support with v1.x was improved, the old staticmethods are restored #82 
**Remove:** :fire: The project no longer raise warning on tiny content given for detection, will be simply logged as warning instead #92 
**Improvement:** :sparkles: The Unicode detection is slightly improved, see #93 
**Bugfix:** :bug: In some rare case, the chunks extractor could cut in between a multi-byte character and could mislead the mess detection #95 
**Bugfix:** :bug: Some rare 'space' characters could trip up the `UnprintablePlugin`/Mess …

Version 2.0.5

---

setup.py

Add shortcut to docs and gh issue (pypi)

:wrench: Add project_urls in setup.py

---

charset_normalizer/md.py

Improvement following report #104 
Some HTML comments could be seen as potential mess and could mislead the main detection.

:wrench: Add character to common ASCII most encountered and safe (MD)

---

charset_normalizer/version.py

Well. This tag fix one urgent matter but come with several others things.
*Changes:*
- **Bugfix:** :bug:  Unforeseen regression with the loss of the backward-compatibility with some older minor of Python 3.5.x #100 
- **Bugfix:** :bug: Fix CLI crash when using --minimal output in certain cases #103
- **Improvement:** :sparkles: Minor improvement to the detection efficiency #106 #101

:bookmark: Version 2.0.6

---

charset_normalizer/api.py

Language detection gave two logging output.

:fire: Remove double logging entry for the same purpose

---

MANIFEST.in
data/NOTICE.md

Following #138 
Address any future questions on this part.

:pencil: Add NOTICE.md for test data

---

CHANGELOG.md
setup.cfg

Eg. This should ease the upstream packaging for OSes.
All notable changes to this project will be documented in this file.
The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),

Add CHANGELOG.md

---

.readthedocs.yaml
docs/conf.py
docs/index.rst
docs/requirements.txt
docs/user/cli.rst

add CLI + theme change to furo

:pencil: Docs improvements

---

charset_normalizer/cli/normalizer.py

https://github.com/Ousret/charset_normalizer/issues/180

CLI default threshold aligned with the API threshold

---

bin/performance.py

Charset-Normalizer / Chardet: Performance Сomparison

Charset-Normalizer / Chardet: performance comparison

---

charset_normalizer/api.py
charset_normalizer/cd.py
charset_normalizer/cli/normalizer.py
charset_normalizer/constant.py
charset_normalizer/md.py
charset_normalizer/models.py
charset_normalizer/utils.py

Immediately following PR https://github.com/Ousret/charset_normalizer/pull/192

:art: Replace AST typing to the native syntax (3.6+)

---

docs/user/advanced_search.rst
docs/user/handling_result.rst
docs/user/miscellaneous.rst

:pencil: Update docs

---

docs/community/speedup.rst

* `--no-binary :all:` is a bit too broad
* Other minor formatting/style fixes

Update speedup docs

---

.github/workflows/ci.yml
build-requirements.txt
dev-requirements.txt
setup.py

and disable debug symbols in generated binary (md)

:arrow_up: mypy/c upgrade to 1.5.1 for python >= 3.8

---

CHANGELOG.md
charset_normalizer/models.py
tests/test_base_detection.py

:bug: relax TypeError with a CharsetMatch instance when trying to compare it with anything else than a CharsetMatch instance

---

pyproject.toml

pyproject.toml: Fix project scripts
