charset_normalizer/normalizer.py
charset_normalizer/probe_chaos.py
test/test_on_byte.py

bugfix division by zero

---

charset_normalizer/normalizer.py
charset_normalizer/version.py
test/test_on_byte.py

Bugfix when passing empty bytes to detector

---

charset_normalizer/version.py
setup.py

:wrench: allow prettytable 2.0 even if they dropped py 3.5

---

charset_normalizer/legacy.py
test/test_detect_legacy.py

In order to be as close as possible to `chardet` behavior regarding the `detect` function,
this PR adjusts the return value when the actual given content contains the SIG (utf-8).
This minor fix is related to the possible integration of this lib to `requests`. see https://github.com/psf/requests/pull/5797
Why does Charset-Normalizer return 'utf-8' instead of 'utf-8-sig'?
Here are the main reasons : 
- The SIG is actually not very useful, and not widely recognized even by the Unicode consortium.
- The detection/normalization process does strip the sig but takes it into account.

:bug: Legacy detect should return UTF-8-SIG if sig is detected

---

charset_normalizer/normalizer.py
test/test_on_byte.py

Related bug discovered by @potiuk see https://github.com/psf/requests/pull/5797#issuecomment-840044183
The exception happens when the payload is empty AND trying to use/uncovers alphabets.
Test added.

:bug: Fix empty payload detection/alphabets listing

---

charset_normalizer/normalizer.py

Linked to https://github.com/psf/requests/pull/5797#issuecomment-840362338

:bug: Fix very rare case of ?bad? bytes payload that cause decode/encode errors

---

charset_normalizer/normalizer.py

`charset_normalizer` imposes logging level and format to others. This PR fixes that issue by using a local `logger` object instead.

:art: Conflicting logging usage

---

.github/workflows/run-tests.yml

The migration from travis-ci to GHA was incomplete.

:heavy_check_mark: GHA tests was not using codecov action publish

---

charset_normalizer/__init__.py
charset_normalizer/hook.py
charset_normalizer/utils.py

I noticed charset_normalizer meddles with `sys.modules`, causing this:
```
>>> import charset_normalizer
>>> import unicodedata
>>> unicodedata
<module 'unicodedata2' from '.../site-packages/unicodedata2.cpython-39-darwin.so'>
```
This PR fixes that by using a fairly standard `try: except ImportError:` guard instead of the `sys.modules` hook.
```
>>> import charset_normalizer
>>> import unicodedata
>>> unicodedata
<module 'unicodedata' from '.../python3.9/lib-dynload/unicodedata.cpython-39-darwin.so'>
```

Don't inject unicodedata2 into sys.modules

---

charset_normalizer/md.py
tests/test_on_byte.py

Close #58~
To reproduce:
```python
from charset_normalizer import from_bytes
results = from_bytes(b"{}").best()
```
Expected encoding = 'ASCII'; Got 'UTF-16 (Variant)'.
Why does this happen?
Because the first pass consists of assessing the "mess/chaos" ratio, and one of the detection plugins was unadjusted for a small JSON payload.

:bug: Fix too small JSON payload triggering md with high ratio

---

charset_normalizer/md.py
tests/test_on_byte.py

Close #62 
This PR addresses mainly ASCII-related issues.

:sparkle: Improvement over ASCII detection, adjust the sensibility of 'ArchaicUpperLowerPlugin'

---

charset_normalizer/api.py
tests/test_on_byte.py

This will be used as a last resort only. In case the detection fails to find any suitable match.
This PR has been made according to some community wishes.

:sparkle: Introducing fallback match for ASCII and UTF-8

---

charset_normalizer/models.py
tests/test_on_byte.py

**Brief:**
Accessing the `alphabets` property of a `CharsetMatch` instance when the original payload contains a surrogate-like character may raise an unexpected exception.
An example/test case is added to ensure this bad case will not happen again.

🐛  Fix accessing the 'alphabets' property when the payload contain surrogate like characters

---

charset_normalizer/md.py
tests/test_probe_chaos.py

**Brief:**
CSVs file may trigger the MD in certain cases. Therefore making the encoding guess much harder.

❇️  Adjust the MD to lower the sensitivity around certain CSVs

---

charset_normalizer/cli/normalizer.py

Unfortunate ending to the CLI script when no encoding has been found.
Given traceback:
```
line 192, in cli_detect
] if args.alternatives else x_[0].__dict__,
UnboundLocalError: local variable 'x_' referenced before assignment
```
Rocky mistake indeed...
In addition to the previous case that has been fixed, the CLI will now output a well JSON output even when there is no encoding that matches the content.

🐛  The CLI no longer raise an unexpected exception when no encoding has been found

---

.github/workflows/chardet-bc.yml
.github/workflows/detector-coverage.yml
.github/workflows/performance.yml
.github/workflows/run-tests.yml
charset_normalizer/md.py
charset_normalizer/utils.py
tests/test_probe_chaos.py

This PR was meticulously made with the latest observations from the community. (Incl. some of my own)
- Excluding ASCII text from the MD plugin `ArchaicUpperLower`
- `is_accentuated` function from utils.py was incomplete, therefore, the MD plugins detection that depended on it was biased.
- Lowered the word count threshold for MD plugin `SuperWierdWord`
- And improve the weird word detection with suspiciously long ones.

🩹 MD sensitivity adjustments (take two)

---

charset_normalizer/api.py

Charset-Normalizer comes with a preemptive encoding detector but until this instant, it was not trusted at all when the MD computed a ratio too high in the first place when decoding using the specified encoding.
Now, with this PR, in case the detection would not find any best suitable match, will use the specified one if it suits the content.

❇️ Allow fallback on specified encoding if any

---

bin/coverage.py

The data-set just got updated with:
- https://github.com/Ousret/char-dataset/commit/479d9f0ac5a3fa959dc7cbbd6a025fdf615942f8
- https://github.com/Ousret/char-dataset/commit/98583f656f6c3c84ea0346e5b5faa7947ebbd986
- https://github.com/Ousret/char-dataset/commit/9294d8d79ec77db83104fa35f93f8d981fda3065
The `coverage.py` script needed some minor adjustments to verify binary files. (None expected)

:sparkle: coverage.py revision to verify if binary files are not seen as text

---

.github/workflows/chardet-bc.yml
.github/workflows/detector-coverage.yml
.github/workflows/integration.yml
.github/workflows/performance.yml
.github/workflows/run-tests.yml

Everything was named "build" and could bring some confusion.
The root `name:` is not sufficient.
+ Set Python 3.10.rc.1 (tests)

:wrench: Proper jobs names for workflows

---

charset_normalizer/__init__.py
charset_normalizer/legacy.py
charset_normalizer/models.py

Something was not quite right with the v1 support regarding:
- `CharsetNormalizerMatches.from_bytes`
- `CharsetNormalizerMatches.from_fp`
- `CharsetNormalizerMatches.from_path`
- `CharsetNormalizerMatches.normalize`
This PR provides a better/cleaner implt.

:art: Proper support for static methods that were in v1.x

---

setup.py

See https://www.python.org/dev/peps/pep-0561/#id18

🍱 Add missing package_data kwarg in setup.py for 'py.typed'

---

charset_normalizer/api.py

Following commit abcb49a9c297590b45aef721bcd64400919d8ea9 
I forgot to add `bytearray` to acceptable types in the `from_bytes` function.

Add bytearray type chk in from_bytes function

---

charset_normalizer/api.py

…
Raising a warning is a bit excessive and seems to bother more than it helped.
The general idea of a warning should be that its fixable by the end user/lib. Most of the time its not.

:fire: Remove the warning (about small content) in favor of a simple logging.warning

---

charset_normalizer/md.py
charset_normalizer/models.py
charset_normalizer/utils.py
tests/test_base_detection.py

Tiny improvement that allow small Unicode payload to be detected with more accuracy.
```python
import charset_normalizer
payload = "😀".encode("utf_8")
results = from_bytes(payload)
print(results.best().encoding)  # print "utf_8"!
```
chardet has trouble with those cases. Any Unicode payload containing emoticons makes the detection fail. Probably their prober that need to be retrained with more up-to-date stats.
```
>>> chardet.detect("😀".encode("utf_8"))
{'encoding': None, 'confidence': 0.0, 'language': None}
```
That a tiny improvement but noticeable/appreciable.

:sparkle: Small improvement over Unicode detection

---

charset_normalizer/api.py
tests/test_base_detection.py

Second attempt following draft #90 
Abstract
---------
When `charset_normalizer` measure the mess/coherence in a given byte sequence for a given encoding, it extract small chunks of data.
Sometime, due to bad luck, it could split the data at the wrong initial index causing the rendered str (for the chunk) to be gibberish.
This PR address that problem and try to find the appropriate start index.

❇️ Improve chunk extraction with multi-byte string

---

.github/workflows/performance.yml

Because Chardet is extremely slow in those cases, the run could take up to an hour to complete!

:wrench: Lower the size increase in medium and big scenario

---

charset_normalizer/md.py

CJK/Ideographic spaces could mislead the mess detection. This fix that!

:wrench: Adjust UnprintablePlugin to ignore "unprintable" spaces like IdeographicSpace

---

charset_normalizer/api.py

First discovered by https://github.com/ros-infrastructure/ros_buildfarm/pull/905 Not all Python 3.5.x are concerned. Latest minor is OK (3.5.10).
Was very unexpected. This PR should fix that promptly.

:bug: Fix ImportError that could occurs on older Python 3.5.x

---

charset_normalizer/md.py

With this PR we push further the detection coverage (less than 1% improvement).
But still noticeable.

:sparkles: Minor improvements for the MD

---

charset_normalizer/cli/normalizer.py
tests/test_cli.py

Happen when used with -a (alternative)
Here is the traceback
```
(venv) [ahmed@fedora charset_normalizer]$ normalizer -a -m ./data/sample.1.fr.srt 
Traceback (most recent call last):
File "/home/ahmed/PycharmProjects/charset_normalizer/venv/bin/normalizer", line 33, in <module>
sys.exit(load_entry_point('charset-normalizer==2.0.6', 'console_scripts', 'normalizer')())
File "/home/ahmed/PycharmProjects/charset_normalizer/venv/lib/python3.9/site-packages/charset_normalizer-2.0.6-py3.9.egg/charset_normalizer/cli/normalizer.py", line 198, in cli_detect
File "/home/ahmed/PycharmProjects/charset_normalizer/venv/lib/python3.9/site-packages/charset_normalizer-2.0.6-py3.9.egg/charset_normalizer/models.py", line 42, in __eq__
TypeError: __eq__ cannot be invoked on <class …
```

:bug: Fix CLI when using --minimal output in certain cases

---

charset_normalizer/cd.py
tests/test_coherence_detection.py

This should improve the detection accuracy regarding some old CP. Although not really needed, its a nice improvement.

:sparkle: Further improve infering the language from a given CP

---

charset_normalizer/__init__.py
charset_normalizer/assets/__init__.py

Following #114 
Some Python environment override the default source encoding and its a problem when used with `charset_normalizer`.
More context available cf. https://bugs.python.org/issue29240
- `charset_normalizer/__init__.py`
- `charset_normalizer/assets/__init__.py`
Add the encoding tag.

:wrench: Trying to leverage PEP263 when PEP3120 is ignored

---

charset_normalizer/cd.py
charset_normalizer/md.py
charset_normalizer/models.py

This PR aim to improve the detection coverage by 1%.
- Improve the Turkish language coherence detection
- Test in a improved order languages based on the source alphabet.

:sparkle: Various detection improvement (MD+CD)

---

charset_normalizer/api.py
charset_normalizer/version.py
tests/test_large_payload.py

Here is a minimal reproducible example.
```python
from charset_normalizer import from_bytes
from charset_normalizer.constant import TOO_BIG_SEQUENCE
def test_misleading_large_sequence():
content = (("hello simple ascii " * TOO_BIG_SEQUENCE) + ('我没有埋怨，磋砣的只是一些时间。 磋砣的只是一些时间。')) .encode('utf_8')
guesses = from_bytes(content)
assert len(guesses) > 0
match = guesses.best()
assert match is not None
assert match.encoding == 'utf_8'
assert str(match) is not None
```
This PR aims to fix that issue.
Close #136

🐛 Fix large (misleading) sequence giving UnicodeDecodeError

---

CHANGELOG.md
charset_normalizer/api.py
tests/test_logging.py

Following PR #135 , accidentally introduced a small regression.

Fix wrong logging level applied when setting kwarg `explain` to True

---

.codecov.yml
CHANGELOG.md
charset_normalizer/api.py

I understand that the latest release unexpectedly generated some noise for some people in specific environments.
The engagement I made with `charset-normalizer` given its wide deployments* still applies. Therefore, regarding : 
- https://github.com/spaam/svtplay-dl/issues/1445
- https://github.com/home-assistant/core/issues/60615
- https://github.com/Ousret/charset_normalizer/issues/145
With this PR I adjust the impact to a minimal impact while keeping backward compatibility.
Fixes/Adress #145 
*: _Listening as broadly as possible regarding any side-effects to the community_

:wrench: Tweak/adjust the logging verbosity greater-eq to warning level

---

CHANGELOG.md
charset_normalizer/api.py

Close #153 
Thanks to the detailed report in #153 I am able to fix a rare edge case.

:bug: Fix fallback match being created when lazystr failed decoding

---

CHANGELOG.md
charset_normalizer/api.py
tests/test_logging.py

The language detection (CD) on ASCII is often useless. With this PR we skip it and globally improve performance.

:wrench: Skipping CD on ASCII

---

CHANGELOG.md
charset_normalizer/version.py

- Fallback match entries might lead to UnicodeDecodeError for large bytes sequence (PR #154)
- Skipping the language-detection (CD) on ASCII (PR #155)

:bookmark: bump version 2.0.10

---

.github/workflows/run-tests.yml
CHANGELOG.md
setup.py

From Python 3.11 CHANGES.
- The Unicode database has been updated to version 14.0.0. (bpo-45190).

Add explicit support for Python 3.11

---

README.md
charset_normalizer/api.py
docs/user/miscellaneous.rst
tests/test_logging.py

Staying as far as humanly possible from any controversial situation.
cf. https://docs.python.org/3/howto/logging.html#custom-levels
A quick search through GH shows that `TRACE` is often assigned to `int:5` but it's not always the case. So to avoid the same situation in another place, I am removing the global assignment.

:fire: Avoid setting/imposing TRACE level for everyone

---

CHANGELOG.md
charset_normalizer/version.py

- Explicit support for Python 3.11 (PR #164)
- The logging behavior has been completely reviewed, now using only TRACE and DEBUG levels (PR #163 #165)

:bookmark: Bump to version 2.0.11

---

.github/workflows/detector-coverage.yml
.github/workflows/python-publish.yml
CHANGELOG.md
charset_normalizer/md.py
charset_normalizer/version.py

The MD plugin `SuperWeirdWordPlugin` is triggered wrongfully around some characters suite.
See https://github.com/streamlink/streamlink/issues/4329#issuecomment-1028866710 for the original payload
See https://github.com/streamlink/streamlink/issues/4329 for the raised issue about it

:bug: Improving the reliability around complex ascii string

---

CHANGELOG.md
bin/bc.py
bin/coverage.py
bin/performance.py
bin/serve.py
charset_normalizer/version.py

Originally, some _master_ playlists (m3u) were miss-detected. This release will prevent the downstream users to be unable to read properly some streams. More on that, see the related PR.
- ASCII miss-detection on rare cases (PR #170)

Release 2.0.12

---

.github/workflows/run-tests.yml

[Python 3.11.0b1 is now available!](https://discuss.python.org/t/python-3-11-0b1-is-now-available/15602?u=hugovk)
Rather than specify alpha 4 as the upper limit on the CI, `3.11-dev` will track the latest available alpha/beta/RC.
(Full release is expected in October.)
https://github.com/hugovk/charset_normalizer/runs/6342369089?check_suite_focus=true

Test latest Python 3.11

---

CHANGELOG.md
charset_normalizer/cli/normalizer.py
charset_normalizer/utils.py

And deprecate the use of unicodedata2

:sparkle: Add unicode version output in CLI --version

---

CHANGELOG.md
README.md
charset_normalizer/version.py

- Output the Unicode table version when running the CLI with `--version` (PR #194)
- Re-use decoded buffer for single byte character sets from [@nijel](https://github.com/nijel) (PR #175)
- Fixing some performance bottlenecks from [@deedy5](https://github.com/deedy5) (PR #183)
- Workaround potential bug in cpython with Zero Width No-Break Space located in Arabic Presentation Forms-B, Unicode 1.1 not acknowledged as space (PR #175)
- CLI default threshold aligned with the API threshold from [@oleksandr-kuzmenko](https://github.com/oleksandr-kuzmenko) (PR #181)
- Support for Python 3.5 (PR #192)
- Use of backport unicodedata from `unicodedata2` as Python is quickly catching up, scheduled for removal in 3.0 (PR #194)

Release 2.1.0

---

charset_normalizer/__init__.py
charset_normalizer/assets/__init__.py

Corrected typos in the name of the encoding. It was in 2 files. In my Django project, because of this, it did not work i18n

fix coding in 2 files

---

.github/workflows/lint.yml
charset_normalizer/api.py
charset_normalizer/cd.py
charset_normalizer/cli/normalizer.py
charset_normalizer/models.py
charset_normalizer/utils.py

Following https://github.com/Ousret/charset_normalizer/issues/182

:art: Enable strict type check and improve the project typing

---

CHANGELOG.md
charset_normalizer/api.py

- Function `normalize` scheduled for removal in 3.0
- Removed useless call to decode in fn is_unprintable (#206)
- Third-party library (i18n xgettext) crashing not recognizing utf_8 with underscore from [@aleksandernovikov](https://github.com/aleksandernovikov) (#204)

Version 2.1.1

---

CHANGELOG.md
charset_normalizer/utils.py
charset_normalizer/version.py

Improve multi-byte cutter/chunk

---

.github/workflows/python-publish.yml
CHANGELOG.md
charset_normalizer/version.py

- Multi-bytes cutter/chunk generator did not always cut correctly (PR #233)
- Speedup provided using mypy/c 0.990 on Python >= 3.7

Release 3.0.1

---

tests/test_logging.py

```
/_pytest/fixtures.py:900: PytestRemovedIn8Warning: Support for nose tests is deprecated and will be removed in a future release.
project/tests/test_logging.py::TestLogBehaviorClass::test_set_stream_handler_format is using nose-specific method: `setup(self)`
To remove this warning, rename it to `setup_method(self)`
See docs: https://docs.pytest.org/en/stable/deprecations.html#support-for-tests-written-for-nose
```

Fix minor pytest deprecation

---

docs/user/cli.rst

A line break is needed for an ordered list to render.

Fix ordered list rendering

---

.github/workflows/mypyc-verify.yml
.github/workflows/python-publish.yml
.github/workflows/run-tests.yml
CHANGELOG.md
README.md
build-requirements.txt
charset_normalizer/version.py
dev-requirements.txt
docs/user/support.rst
setup.cfg

Starting off next release >=3.1.0

:fire: Drop the support for EOL Python 3.6

---

CHANGELOG.md
charset_normalizer/legacy.py

Update the legacy "detect" function to match chardet signature.
Also, disregard any new parameters that could be added in the future.

:sparkle: Support recently added "should_rename_legacy" in function detect (legacy)

---

README.md

Emoji shortcodes vary from platform to platform and aren't supportted by purely markdown and pypi. Replacing emoji shortcodes with UTF-8 emoji like others in README can make the document more consistent.

Replace emoji shortcodes with UTF-8 emoji

---

.github/workflows/cd.yml
.github/workflows/ci.yml
CHANGELOG.md
charset_normalizer/__init__.py
charset_normalizer/api.py
charset_normalizer/md.py
charset_normalizer/utils.py
charset_normalizer/version.py
docs/api.rst
docs/index.rst
docs/user/miscellaneous.rst
setup.cfg
tests/test_isbinary.py

- Typehint for function `from_path` no longer enforce `PathLike` as its first argument
- Minor improvement over the global detection reliability
- Introduce function `is_binary` that relies on main capabilities, and is optimized to detect binaries
- Explicit support for Python 3.12
- Edge case detection failure where a file would contain 'very-long' camel-cased word (Issue #289)

Release 3.2.0

---

CHANGELOG.md
README.md
bin/bc.py
charset_normalizer/constant.py
docs/user/support.rst

Close #323 
List of added references:
```python
IANA_NO_ALIASES = [
"cp720",
"cp737",
"cp856",
"cp874",
"cp875",
"cp1006",
"koi8_r",
"koi8_t",
"koi8_u",
]
```

:sparkle: Add support for (nine) encoding that have no aliases

---

CHANGELOG.md
charset_normalizer/models.py

:bug: Fix unreachable code in the sorting algorithm of CharsetMatch

---

CHANGELOG.md
bin/coverage.py
charset_normalizer/md.py
charset_normalizer/utils.py
charset_normalizer/version.py
tests/test_edge_case.py

:sparkle: Improve the detection around some cases

---

.github/workflows/cd.yml
.github/workflows/ci.yml
CHANGELOG.md
build-requirements.txt
dev-requirements.txt

- Optional mypyc compilation upgraded to version 1.6.1 for Python >= 3.8
- Improved the general detection reliability based on reports from the community

:bookmark: Release 3.3.1

---

CHANGELOG.md
charset_normalizer/models.py
charset_normalizer/version.py

:bug: Fix unintentional memory usage regression when using large payload that match several encoding (#376)

---

charset_normalizer/legacy.py

when I write something like:
```python3
x = charset_normalizer.detect(...)["encoding"]
```
`x` is inferred as `str | float | None` instead of actual `str | None`.
use custom `TypedDict` type as the return type of `detect` method if Python version >= 3.8.
(`TypedDict` is not available in Python 3.7)

use TypedDict for return type of legacy detect()

---

CHANGELOG.md
charset_normalizer/api.py
charset_normalizer/constant.py
charset_normalizer/md.py
charset_normalizer/version.py

Issues (#520) (#509) (#498) (#407)

:wrench: improve the detector general reliability

---

CHANGELOG.md
charset_normalizer/api.py
charset_normalizer/cli/__main__.py
charset_normalizer/models.py
docs/community/featured.rst
tests/test_edge_case.py
tests/test_preemptive_detection.py

fix html file is not reported as UTF8 after conversion

---

CHANGELOG.md
charset_normalizer/api.py
charset_normalizer/models.py

:wrench: improve detector based on case 537

---

.github/workflows/cd.yml
.github/workflows/ci.yml
build-requirements.txt
dev-requirements.txt
setup.cfg

Related:
- CI blocked by https://github.com/mypyc/mypyc/issues/1056

Support Python 3.13

---

CHANGELOG.md

- Addressed the DeprecationWarning in our CLI regarding `argparse.FileType` by backporting the target class into the package. (#591)
- Improved the overall reliability of the detector with CJK Ideographs. (#605) (#587)
- Optional mypyc compilation upgraded to version 1.15 for Python >= 3.8

:bookmark: Release 3.4.2

---

.github/workflows/cd.yml
.github/workflows/ci.yml
.github/workflows/codeql.yml
CHANGELOG.md
MANIFEST.in
README.md
_mypyc_hook/backend.py
noxfile.py
pyproject.toml
setup.py
src/charset_normalizer/api.py
src/charset_normalizer/legacy.py
src/charset_normalizer/version.py
tests/test_base_detection.py
tests/test_detect_legacy.py

- mypy(c) is no longer a required dependency at build time if `CHARSET_NORMALIZER_USE_MYPYC` isn't set to `1`. (#595) (#583)
- automatically lower confidence on small bytes samples that are not Unicode in `detect` output legacy function. (#391)
- Custom build backend to overcome inability to mark mypy as an optional dependency in the build phase.
- Support for Python 3.14
- sdist archive contained useless directories.
- automatically fallback on valid UTF-16 or UTF-32 even if the md says it's noisy. (#633)
- SBOM are automatically published to the relevant GitHub release to comply with regulatory changes.
Each published wheel comes with its SBOM. We choose CycloneDX as the format.
- Prebuilt optimized wheel are no longer distributed by default for CPython 3.7 due to a change in …

Release 3.4.3
